[package]
name = "iu"
version = "0.0.1"
entrypoint = "lib.typ"
authors = ["Michael Albertz"]
license = "MIT"
description = "Template for academic papers at the IU International University."

homepage = "https://github.com/Prioe/typst-template-iu"
repository = "https://github.com/Prioe/typst-template-iu"
